version: '3.9'

services:
  db:
    container_name: blog_api
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: 0m6jse@_@447
      POSTGRES_DB:  blog_api

    ports:
      - 5432:5432
